export const CONTENT_BLOCK_TYPE = Object.freeze({
  HEADING: 'HEADING',
  PARAGRAPH: 'PARAGRAPH',
  EXAMPLE: 'EXAMPLE',
  REAL_WORLD_EXAMPLE: 'REAL_WORLD_EXAMPLE',
  COMMON_MISTAKE: 'COMMON_MISTAKE',
  WARNING: 'WARNING',
  TIP: 'TIP',
  CODE: 'CODE',
  QUIZ_REFERENCE: 'QUIZ_REFERENCE',
  VIDEO_REFERENCE: 'VIDEO_REFERENCE',
});

export const TOPIC_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PUBLISHED: 'PUBLISHED',
  FLAGGED: 'FLAGGED',
});
