export const NODE_PROGRESS_STATUS = Object.freeze({
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  NEEDS_REVISION: 'NEEDS_REVISION',
});

export const NODE_PROGRESS_LABELS = Object.freeze({
  [NODE_PROGRESS_STATUS.NOT_STARTED]: 'Not started',
  [NODE_PROGRESS_STATUS.IN_PROGRESS]: 'In progress',
  [NODE_PROGRESS_STATUS.COMPLETED]: 'Completed',
  [NODE_PROGRESS_STATUS.NEEDS_REVISION]: 'Needs revision',
});
